"""
Contains lists of words used for generating memorable random aliases.
"""

ADJECTIVES = [
    "adaptable", "adventurous", "affectionate", "agile", "alert", "amiable", "amused",
    "balanced", "blue", "bold", "brave", "bright", "brisk", "busy",
    "calm", "capable", "careful", "charming", "cheerful", "clever", "coherent",
    "competent", "composed", "creative", "crisp", "crucial", "curious",
    "daring", "dazzling", "decisive", "deep", "devoted", "diligent", "direct",
    "dynamic", "eager", "early", "easy", "elastic", "elated", "elegant", "eminent",
    "enchanting", "ethical", "excited", "expert", "faint", "fair", "fancy", "fast",
    "fearless", "fine", "firm", "flying", "focused", "frank", "fresh", "frosty",
    "gentle", "giving", "glad", "gleaming", "golden", "good", "graceful", "grand",
    "grateful", "great", "green", "happy", "harmonious", "helpful", "honest", "hopeful",
    "humble", "humorous", "ideal", "jolly", "joyful", "keen", "kind", "knowing",
    "large", "lavish", "learned", "level", "light", "lively", "logical", "loving",
    "loyal", "lucky", "magical", "major", "modern", "modest", "moving", "musical",
    "neat", "noble", "nimble", "optimal", "orange", "orderly", "placid", "playful",
    "polite", "positive", "potent", "proven", "proud", "purple", "quick", "quiet",
    "radiant", "rapid", "rational", "ready", "regal", "related", "relaxed", "robust",
    "rosy", "round", "royal", "secure", "serene", "sharp", "shining", "simple",
    "sincere", "skilled", "sleepy", "smart", "smooth", "social", "solid", "special",
    "stable", "stellar", "still", "strong", "subtle", "sunny", "super", "swift",
    "thankful", "thriving", "tidy", "timely", "topaz", "trusty", "truthful", "upbeat",
    "useful", "valid", "vast", "verbal", "vibrant", "violet", "vivid", "warm", "watchful",
    "willing", "wise", "witty", "worthy", "yellow", "young", "zesty"
]

NOUNS = [
    "acorn", "anchor", "apple", "apricot", "arrow", "award", "axis", "baker", "banana",
    "beacon", "beagle", "beans", "bear", "bee", "berry", "bird", "bison", "bloom",
    "boat", "bonus", "book", "breeze", "brook", "brush", "buddy", "bulb", "bunny",
    "cabin", "camel", "candy", "canyon", "car", "castle", "cat", "cedar", "cello",
    "charm", "cherry", "chime", "cicada", "citrus", "cloud", "clover", "coast", "comet",
    "coral", "corgi", "crane", "crest", "cupid", "daisy", "dancer", "delta", "diamond",
    "dingo", "diver", "dog", "dolphin", "donkey", "dove", "dragon", "dream", "driver",
    "droplet", "druid", "drum", "duck", "dune", "eagle", "echo", "ember", "engine",
    "falcon", "family", "field", "fish", "flame", "fleet", "flicker", "flute", "foam",
    "forest", "fox", "friend", "frog", "frost", "galaxy", "gator", "gem", "genius",
    "geyser", "gift", "ginger", "glade", "glider", "gnome", "goat", "grape", "grass",
    "griffin", "grove", "guard", "guitar", "gull", "hiker", "hippo", "hobby", "honey",
    "horse", "house", "hummingbird", "hydra", "icon", "idea", "igloo", "image", "ink",
    "island", "item", "ivy", "jacket", "jaguar", "jazz", "jeep", "jelly", "jewel",
    "joker", "judo", "juice", "jungle", "juniper", "kayak", "key", "kite", "kiwi",
    "koala", "lagoon", "lake", "lamb", "lantern", "lark", "laser", "leaf", "lemon",
    "leo", "leopard", "level", "light", "lily", "lime", "lion", "lizard", "llama",
    "local", "locket", "logic", "lotus", "lumen", "lynx", "magic", "magnet", "mango",
    "maple", "marble", "marker", "maven", "melon", "mink", "mint", "mirage", "mixer",
    "mobile", "model", "mole", "monkey", "moose", "moral", "mosaic", "motion", "motor",
    "mouse", "muse", "music", "mustang", "nectar", "nest", "nexus", "ninja", "noodle",
    "note", "novel", "nugget", "nutmeg", "oasis", "ocean", "olive", "onion", "opal",
    "oracle", "orca", "orchid", "otter", "owl", "oyster", "panda", "papaya", "parrot",
    "pasta", "patch", "path", "peace", "peach", "pearl", "pecan", "pegasus", "pelican",
    "pencil", "pepper", "petal", "phoenix", "piano", "pie", "pilot", "pine", "pink",
    "pixel", "pizza", "planet", "plaza", "plum", "poet", "pony", "poppy", "portal",
    "prairie", "prize", "proxy", "puma", "puzzle", "python", "quail", "quest", "quill",
    "rabbit", "radar", "radius", "raven", "realm", "relic", "rhino", "rider", "ridge",
    "river", "road", "robin", "robot", "rocket", "rook", "rose", "rover", "ruby",
    "saga", "sailor", "salmon", "salsa", "sand", "sapphire", "scarf", "scope", "scout",
    "seal", "seed", "sequoia", "serpent", "shadow", "shark", "shell", "shield", "ship",
    "shrimp", "signal", "silk", "skate", "skier", "sky", "sloth", "snail", "snake",
    "snow", "soap", "solar", "song", "soul", "spade", "spark", "sparrow", "spear",
    "spirit", "spoon", "sprout", "spruce", "spy", "squid", "stable", "stage", "stamp",
    "star", "statue", "stingray", "stone", "story", "stream", "street", "studio", "sugar",
    "sun", "surf", "swallow", "swan", "swift", "sword", "syrup", "taco", "talent",
    "tiger", "timber", "toast", "token", "tomato", "topaz", "torch", "toucan", "tower",
    "toy", "tractor", "trail", "train", "travel", "treat", "tree", "tribal", "trident",
    "trout", "tuba", "tulip", "tuna", "tundra", "turtle", "tutor", "twig", "ultra",
    "unicorn", "uniform", "union", "unity", "update", "vector", "velvet", "venus",
    "video", "vine", "violet", "viper", "vision", "vista", "vixen", "vortex", "voyage",
    "wagon", "wallet", "walnut", "walrus", "watch", "wave", "weaver", "whale", "wheat",
    "wheel", "whisk", "willow", "wind", "wing", "wizard", "wolf", "wonder", "wood",
    "world", "worm", "writer", "xenon", "yacht", "yak", "yarn", "year", "yeti", "yoga",
    "yogurt", "yoyo", "zebra", "zenith", "zephyr", "zero", "zest", "zipper", "zodiac",
    "zone", "zoom"
]