name: Deploy to GCP
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # For Workload Identity Federation
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/your-pool-name/providers/your-provider-name' # Replace
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}' # Replace
    - uses: hashicorp/setup-terraform@v2
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
      # Terraform google_cloudfunctions2_function resource should handle code deployment from source